packages:
  - 'packages/e2e'
  - 'packages/@wdio_electron-types'
  - 'packages/@wdio_electron-utils'
  - 'packages/wdio-electron-service'
  - 'apps/builder-cjs'
  - 'apps/builder-esm'
  - 'apps/forge-cjs'
  - 'apps/forge-esm'
