packages:
  - 'packages/e2e'
  - 'packages/@wdio-electron_types'
  - 'packages/@wdio-electron_utils'
  - 'packages/wdio-electron-service'
  - 'apps/builder-cjs'
  - 'apps/builder-esm'
  - 'apps/forge-cjs'
  - 'apps/forge-esm'
