name: CI

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:

env:
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [20.x]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache pnpm modules
        uses: actions/cache@v4
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-
      - uses: pnpm/action-setup@v3
        with:
          version: 9.5.0
          run_install: false
      - name: Set pnpm store path
        run: |
          pnpm config set store-dir ~/.pnpm-store --global
      - name: Install Dependencies
        run: |
          pnpm install
          if [ "$RUNNER_OS" == "Windows" ]; then
            pnpm run ci:init-windows
            pnpm install --no-frozen-lockfile
          fi
        shell: bash
      - name: Run Tests
        run: |
          pnpm run ci
        shell: bash
      - name: Run OS-specific Tests
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            pnpm run ci:e2e:clean
            pnpm install --no-frozen-lockfile
            pnpm run ci:e2e:mac-universal
          fi
        shell: bash
      - name: 🐛 Debug Build
        uses: stateful/vscode-server-action@v1
        if: failure()
        with:
          timeout: '180000'
